# -*- coding: utf-8 -*-
"""akshon1

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NeS-ZYmQ_XNihMI1_QY5EPtMboSZ3A6y
"""

#1
print("Twinkle,Twinkle, little star.")
print("How I wonder what you are!")
print("Up above the world so high,")
print("Like a diamond in the sky.")
print("Twinkle,Twinkle, little star.")
print("How I wonder what you are!")

f=input("enter first name")
l=input("enter last name")
print(l," ",f)

#3
r=int(input("enter radius of circle"))
a=22/7*r**2
print("area of circle",a)

#4
color_list = ["Red","Green","White" ,"Black"]
print(color_list[0],color_list[3])

n=input("enter number ")
k=n+n
l=n+n+n
z=int(n)+int(k)+int(l)
print(z)

x = str(input("Enter the number: ")).split(",")
print(x)
x = tuple(x)
print(x)

celsius = float(input("Enetr the temperature in celsius: "))
fahrenheit = 1.8*celsius + 32
print(fahrenheit)

x=int(input("enter number"))
if(x%2==0):
    print("entered number is even")
else:
    print("number is odd")

a=int(input("enter year "))
if (a%100!=0):
    if(a%4==0):
        print("leap year")
    else:
        print("no leap year")
elif (a%100==0):
    if(a%400==0):
        print("leap year")
    else:
        print("no leap year")

x1,y1 = int(input("x1:")), int(input("y1:"))
x2,y2 = int(input("x2:")), int(input("y2:"))
distance = ((x2 - x1)**2 + (y2 - y1)**2)**0.5
print(distance)

p=int(input("enter first angle"))
s=int(input("enter second angle"))
r=int(input("enter third angle"))
g=p+r+s
if (g==180):
    print("angles can form traingle")
else:
    print("cannot form triangle")

principle ,rate ,time = int(input("principle: ")), int(input("rate: ")), int(input("time: "))
CI = principle*((1+rate)**time)
print(CI)

b=int(input("enter number"))
count=0
for i in range(2,b):
    if(b%i==0):
        count=count+1
if(count>0):
        print("not prime")
else:
        print("prime cuhh")

v=int(input("enter number"))
qq=0
for i in range(1,v+1):
    qq=qq+i**2
print(qq)